FROM alpine:3.13.5 AS builder

# COPY APP SOURCES
COPY app /app
WORKDIR /app

# INSTALL DEPENDENCIES
RUN apk add --no-cache npm && \
    npm i -g pkg

# BUNDLE INTO SINGLE EXECUTABLE
RUN pkg .

# USE LEAN CONTAINER
FROM alpine:3.13.5
COPY --from=builder /app/dist/qark-cli-arm64 /usr/local/bin/qark-cli
ENTRYPOINT [ "/usr/local/bin/qark-cli" ]
