FROM alpine:3.13.5 AS builder

# COPY APP SOURCES
COPY app /app
WORKDIR /app

# DEFINE NODE, NPM AND NEXE VERSIONS
ENV NODE_VERSION=12.9.1
ENV NPM_VERSION=7.6.3
ENV NEXE_VERSION=v3.3.7

# INSTALL DEPENDENCIES
RUN apk add --no-cache npm && \
    npm i -g pkg

# BUNDLE INTO SINGLE EXECUTABLE
RUN pkg .

# USE LEAN CONTAINER
FROM alpine:3.13.5
COPY --from=builder /app/dist/qark-cli-arm64 /usr/local/bin/qark-cli
ENTRYPOINT [ "/usr/local/bin/qark-cli" ]
